apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-globaldrum-com
  namespace: default
spec:
  secretName: test-globaldrum-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - test.globaldrum.com
