apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackstock-nginx
  labels:
    app: blackstock-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackstock-nginx
  template:
    metadata:
      labels:
        app: blackstock-nginx
    spec:
      containers:
      - name: caddy 
        image: caddy 
        ports:
        - containerPort: 80
        volumeMounts:
          - name: caddy-config
            mountPath: /usr/share/caddy
          - name: caddy-config-test
            mountPath: /usr/share/caddy/test
      volumes:
        - name: caddy-config
          configMap:
            name: caddy-index-file 
        - name: caddy-config-test
          configMap:
            name: caddy-test-file 
---
apiVersion: v1
kind: Service
metadata:
  name: blackstock-nginx-service
spec:
  selector:
    app: blackstock-nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30013
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blackstock-nginx-ingress
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`www.blackstock.ml`)
    kind: Rule
    services:
    - name: blackstock-nginx-service
      port: 80
    middlewares:
      - name: redirect-https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blackstock-nginx-ingress-ssl
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`www.blackstock.ml`)
    kind: Rule
    services:
    - name: blackstock-nginx-service
      port: 80
  tls:
    secretName: www-blackstock-ml-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
