apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-globaldrum-ml
  namespace: default
spec:
  secretName: jenkins-globaldrum-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - jenkins.globaldrum.com 
